name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: ☕ Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v4
      - run: ./gradlew shadowJar -Pplatform=windows
      - name: Archive package
        uses: actions/upload-artifact@v3
        with:
          name: chatclient
          path: build/libs/chatclient-all.jar